import {
    FaDiagramProject,
    FaEnvelope,
    FaFacebookF,
    FaGithub,
    FaHouse,
    FaInstagram,
    FaLinkedinIn,
    FaRenren,
    FaUser,
    FaYoutube,
    FaBriefcase,
} from "react-icons/fa6";
import {
    BeachEvents,
    FridgeManagerApp,
    keylogger,
    Pokemon,
    airbrush,
    chatbot,
    fraudShieldImg,
    optiLearnImg,
    brightMindImg,
    schedulEaseImg,
} from "../assets";



export const Socials = [
    {
        id: `linkedin-${Date.now()}`,
        label: "LinkedIn",
        Icon: FaLinkedinIn,
        uri: "https://www.linkedin.com/in/dhruvgorasiya/",
        color: "#0072b1",
    },
    {
        id: `github-${Date.now()}`,
        label: "GitHub",
        Icon: FaGithub,
        uri: "https://github.com/DhruvGorasiya",
        color: "#fff",
    },
];

export const Menus = [
    {
        id: `home-${Date.now()}`,
        Icon: FaHouse,
        uri: "#home",
        name: "Home",
    },
    {
        id: `about-${Date.now()}`,
        Icon: FaUser,
        uri: "#about",
        name: "About",
    },
    {
        id: `experience-${Date.now()}`,
        Icon: FaBriefcase,
        uri: "#experience",
        name: "Experience",
    },
    {
        id: `skills-${Date.now()}`,
        Icon: FaRenren,
        uri: "#skills",
        name: "Skills",
    },
    {
        id: `projects-${Date.now()}`,
        Icon: FaDiagramProject,
        uri: "#projects",
        name: "Projects",
    },
    {
        id: `contact-${Date.now()}`,
        Icon: FaEnvelope,
        uri: "#contact",
        name: "Contact",
    },
];

export const ExperiencesData = [
    {
        role: "Software Engineering Intern",
        company: "Weaviate",
        companyUrl: "https://weaviate.io",
        location: "Boston, MA",
        duration: "Aug 2025 – Present",
        highlights: [
            "Scaled RAG pipelines to handle millions of documents, increasing end-to-end throughput by ~30% via parallel ingestion, hybrid search, and metadata filtering.",
            "Drove p95 query latency to <200ms for 95% of requests by prototyping concurrency-safe microservices and tuning index/ANN parameters across multi-node clusters.",
            "Upgraded the Dify Weaviate plugin from v3 → v4, fixing hybrid & generative search paths, schema management, and cloud/local connectivity.",
            "Built telemetry dashboards (latency, throughput, error distribution) and alerts that cut debugging cycles ~40%, enabling proactive recovery and faster incident triage.",
            "Delivered an end-to-end Box demo showcasing ingestion → chunking → hybrid retrieval → LLM generation; refactored auth and search modules per PM feedback.",
            "Wrote integration guides and reusable API recipes that standardized reliability practices and reduced 'first successful query' time for new users.",
            "Coordinated on a partner workflow (Orkes + Weaviate), documenting event-driven retrieval patterns for production RAG systems.",
            "Stress-tested ingestion and query paths under sharded datasets, introduced backpressure and batching, documented ANN cost/perf trade-offs.",
        ],
    },
    {
        role: "Teaching Assistant, MLOps",
        company: "Northeastern University",
        companyUrl: null,
        location: "Boston, MA",
        duration: "Jan 2025 – May 2025",
        highlights: [
            "Supported 60+ students across MLOps course covering model deployment, CI/CD pipelines, and production ML systems.",
            "Held weekly office hours and reviewed assignments on Docker, Kubernetes, and cloud infrastructure (AWS/GCP).",
            "Collaborated with course instructor to design rubrics and provide technical feedback on student projects.",
        ],
    },
    {
        role: "Founder & CTO",
        company: "Twinly",
        companyUrl: "https://twinly.net",
        location: "Boston, MA",
        duration: "Mar 2025 – Jul 2025",
        highlights: [
            "Founded and led Twinly, integrating with Gmail, Notion, Slack, and Google Calendar—reducing context switching by 35% in early trials.",
            "Architected a full-stack system using Next.js, FastAPI, PostgreSQL, and Pinecone enabling low-latency RAG over 10,000+ vectorized memory objects.",
            "Designed and fine-tuned personalized AI agents using GPT-4o, increasing action relevance by 30% through feedback loops and similarity-based threshold optimization.",
            "Implemented secure OAuth and cross-platform API integrations, maintaining 98%+ uptime on GCP Cloud Run.",
            "Led a team of 3 developers to ship the MVP 3 weeks ahead of schedule, onboarding 15+ beta users.",
        ],
    },
    {
        role: "Research Assistant – Machine Learning",
        company: "California State University, Long Beach",
        companyUrl: null,
        location: "Long Beach, CA",
        duration: "Aug 2023 – Jun 2024",
        highlights: [
            "Developed a containment-optimized LSH Ensemble variant achieving 22% reduction in query latency across 5,000+ heterogeneous tables.",
            "Built a hybrid similarity model combining Minhash, q-grams, and word embeddings, boosting attribute-matching precision by 14%.",
            "Engineered an adaptive partitioning system with cost-based rebalancing that reduced false positives by 27% in similarity searches.",
            "Architected a Python pipeline integrating FastText and Scikit-learn for scalable benchmarking via custom hash-based indexing.",
        ],
    },
    {
        role: "Computer Science Tutor",
        company: "California State University, Long Beach",
        companyUrl: null,
        location: "Long Beach, CA",
        duration: "Aug 2023 – Dec 2023",
        highlights: [
            "Mentored 20+ students in advanced CS topics, creating personalized learning approaches that improved comprehension and academic performance.",
            "Facilitated code review sessions emphasizing clean coding practices and industry-standard development techniques.",
            "Developed debugging workshops that improved independent bug resolution by 30% among students.",
            "Created study materials for Data Structures and Algorithms, achieving an average 15% grade improvement.",
        ],
    },
];

export const SkillsData = [
    { name: "Python · Django · Flask · FastAPI", proficiency: "expert" },
    { name: "AWS · GCP · Azure · Docker", proficiency: "expert" },
    { name: "Weaviate · Pinecone · Vector Search", proficiency: "expert" },
    { name: "JavaScript · Node.js · React · Next.js", proficiency: "advanced" },
    { name: "TensorFlow · PyTorch · Scikit-learn", proficiency: "advanced" },
    { name: "PostgreSQL · MongoDB · MySQL · Firebase", proficiency: "advanced" },
    { name: "Java · Spring Boot", proficiency: "advanced" },
    { name: "FastAPI · REST · GraphQL", proficiency: "advanced" },
    { name: "OpenCV · Computer Vision", proficiency: "intermediate" },
    { name: "React Native", proficiency: "intermediate" },
];

export const ProjectsData = [
    {
        id: 1,
        imgSrc: fraudShieldImg,
        name: "FraudShield",
        description: "Real-time fraud detection pipeline for millions of transactions using ML classification and sampling strategies.",
        gitURL: "https://github.com/DhruvGorasiya/Fraudulent-Transaction-Detection",
        techStack: ["Python", "Scikit-learn", "Pandas"],
    },
    {
        id: 2,
        imgSrc: optiLearnImg,
        name: "OptiLearn",
        description: "Intelligent course scheduler that minimizes cognitive load using genetic algorithms and performance feedback.",
        gitURL: "https://github.com/DhruvGorasiya/OptiLearn",
        techStack: ["Python", "Flask", "React", "Genetic Algorithm"],
    },
    {
        id: 3,
        imgSrc: brightMindImg,
        name: "BrightMind",
        description: "AI tutoring system that adapts to individual learning styles using reinforcement learning and NLP.",
        gitURL: "https://github.com/DhruvGorasiya/Brightmind",
        techStack: ["Python", "NLP", "Reinforcement Learning"],
    },
    {
        id: 4,
        imgSrc: schedulEaseImg,
        name: "SchedulEase",
        description: "Smart event scheduling tool that adapts to real-world constraints with data-driven optimization.",
        gitURL: "https://github.com/DhruvGorasiya/SchedulEase",
        techStack: ["React", "Node.js", "MongoDB"],
    },
    {
        id: 5,
        imgSrc: chatbot,
        name: "Chatbot",
        description: "Domain-specific chatbot powered by GPT-4 and Pinecone with vector embeddings and conversation history.",
        gitURL: "https://github.com/DhruvGorasiya/Chatbot",
        techStack: ["OpenAI GPT-4", "Pinecone", "Python"],
    },
    {
        id: 6,
        imgSrc: BeachEvents,
        name: "BeachEvents",
        description: "Cross-platform mobile app for CSULB students with real-time campus events and club updates.",
        gitURL: "https://github.com/orgs/BeachEvents/teams/dev/repositories",
        techStack: ["React Native", "Django", "MongoDB"],
    },
    {
        id: 7,
        imgSrc: keylogger,
        name: "Keylogger",
        description: "Python-based keystroke capture tool that securely transmits data to a configured email address.",
        gitURL: "https://github.com/DhruvGorasiya/Keylogger",
        techStack: ["Python"],
    },
    {
        id: 8,
        imgSrc: FridgeManagerApp,
        name: "Fridge Helper",
        description: "Django web app that eliminates food waste with automated expiry alerts and multi-account sharing.",
        gitURL: "https://github.com/DhruvGorasiya/fridgeHelper/tree/main/FridgeManagerProject",
        techStack: ["Django", "Python"],
    },
    {
        id: 9,
        imgSrc: Pokemon,
        name: "Pokemon",
        description: "Command-line Pokémon game with a captivating storyline, exploration, battles, and creature capture.",
        gitURL: "https://github.com/DhruvGorasiya/Pokemon",
        techStack: ["Python"],
    },
    {
        id: 10,
        imgSrc: airbrush,
        name: "AirBrush",
        description: "Computer vision app that lets users paint virtually in the air using hand gestures via webcam.",
        gitURL: "https://github.com/DhruvGorasiya/AirBrush",
        techStack: ["Python", "OpenCV"],
    },
];
